### ISSUE TITLE
Support more LLMs

### ISSUE THREAD

**Issue by chymian** [rnadigital/agentcloud#142]
**Is your feature request related to a problem? Please describe.**
Local LLMs are not suficent supported.

**Describe the solution you'd like**
since most of the local loader, like ollama, ooba's, etc all support openAI API >= 1.0, we would just need a BASE_URL field to fill in our local path to API.
the LLMstudio (which is not opensource.) entry had such a field, but it's gone.

**Describe alternatives you've considered**
Build in litellm.ai as access to 100+ llms

**Additional context**

**Comment by tomlynchRNA** [comment]
llama2 on ollama, works but its a little bit dumb (cant pick the right tool). working on improving this and adding support for many more.
![image](https://github.com/rnadigital/agentcloud/assets/111718755/08c97c46-609e-47b3-abb8-1779d934d33f)
![image](https://github.com/rnadigital/agentcloud/assets/111718755/6de145d2-67ee-4699-bf6e-84edad033d07)
![image](https://github.com/rnadigital/agentcloud/assets/111718755/9045b15a-074e-4a37-86c7-d9f4a68849c6)

**Comment by tomlynchRNA** [comment]
@charl3sj priority list for models to implement:

vertex https://python.langchain.com/docs/integrations/chat/google_vertex_ai_palm/
groq https://python.langchain.com/docs/integrations/chat/groq/
anthropic https://python.langchain.com/docs/integrations/chat/anthropic/
huggingface https://python.langchain.com/docs/integrations/chat/huggingface/
cohere https://python.langchain.com/docs/integrations/chat/cohere/
mistral https://python.langchain.com/docs/integrations/chat/mistralai/

**Comment by chymian** [comment]
> @charl3sj priority list for models to implement:
> 
> * [ ]  vertex https://python.langchain.com/docs/integrations/chat/google_vertex_ai_palm/
> * [ ]  groq https://python.langchain.com/docs/integrations/chat/groq/
> * [ ]  anthropic https://python.langchain.com/docs/integrations/chat/anthropic/
> * [ ]  huggingface https://python.langchain.com/docs/integrations/chat/huggingface/
> * [ ]  cohere https://python.langchain.com/docs/integrations/chat/cohere/
> * [ ]  mistral https://python.langchain.com/docs/integrations/chat/mistralai/

did you have a look at [litellm.ai](https://github.com/BerriAI/litellm)? 
one solution to rule them all ;)
