### ISSUE TITLE
Enable advanced retrieval strategies

### ISSUE THREAD

**Issue by ragyabraham** [rnadigital/agentcloud#151]
**Problem**
At the moment the way the `agent_backend` does retrieval is very primitive. 

**Proposed Solution**
We need to enable more advanced retrieval strategies by taking advantage of Langchain retrieval method

**Comment by charl3sj** [comment]
@tomlynchRNA Created [this](https://github.com/rnadigital/agentcloud/commits/retrievers/) branch for this enhancement.

The Retriever model with expected keys is [here](https://github.com/rnadigital/agentcloud/blob/787e88349bb90c97c8828f1cb8be2d4bc2c27d12/agent-backend/src/models/mongo.py#L74). I've also added more models with the expected config for each retriever type (subsequent lines) which are commented for now (see [diff](https://github.com/rnadigital/agentcloud/commit/787e88349bb90c97c8828f1cb8be2d4bc2c27d12#)) but should hopefully serve as a reference for expected changes.

**Comment by tomlynchRNA** [comment]
Perfect thanks :+1:
