### ISSUE TITLE
RBAC TODOs

### ISSUE THREAD

**Issue by tomlynchRNA** [rnadigital/agentcloud#160]
- [ ] custom roles
  - [ ] create custom role
  - [ ] apply custom role
  - [ ] delete custom role 
- [x] Ability to change ownerId of teams (if you are the current ownerId or have ORG_OWNER perm)
- [x] create some builtin roles
- [x] add permission checks in router
- [x] #175

**Comment by tomlynchRNA** [comment]
ref #175 need to add perms for that

**Comment by ragyabraham** [comment]
@tomlynchRNA is this issue in progress??
