### ISSUE TITLE
Stand up Cloud infrastructure

### ISSUE THREAD

**Issue by anada10** [rnadigital/agentcloud#163]
Cloud edition to be setup on GCP using Pulumi IAC and available on app.agentcloud.dev

- [ ] pulumi script

acceptance criteria
- ETL data
- RAG data

Blockers:
- authenticating to Google cloud using `GOOGLE_APPLICATION_CREDENTIAL` env variable

**Comment by ragyabraham** [comment]
This is now done and is stable
