### ISSUE TITLE
Simplify Conversation App setup

### ISSUE THREAD

**Issue by anada10** [rnadigital/agentcloud#169]
Currently Conversation apps, have dependencies on setting up Tasks and Agents in the GUI.
We want to dramatically simplify setup of a conversation app, so that it's a single form and users only need to populate 
- Model credentials (e.g. default to gpt 4)
- Provide any datasources
We would provide a default templated agent and auto populate any task configuration so that it would work within the current framework (Crew).

**Comment by tomlynchRNA** [comment]
<details>
<summary>notes</summary>

> cat x
App:
	avatar
	app name
	app description
	model
	welcome message(s)

Tools list:
	pick

Datasources list:
	pick

Agent:
	name
	system message
	variables list

Model:
	type:
	<depends on form>

> cat x2
App:
	avatar
	app name
	app description
	model
	tasks: populated by prebiult rag task
	agents: populated by prebuilt agent
	process: always sequential
	chat manager model: whatever model they pick in the form

Task:
	name: prepopulated
	description: prepopulated
	execpted output: prepopulated
	tools: prepopulated with human_input, box to select datasources
	preferred agent: default to whatever agent was created

Agent:
	name
	role, goal, backstory: prepopulated
	system message
	allow delegation: false
	verbose: always true
	tools: prepopulated with human_input, box to select datasources

Model:
	name: prepopulated
	<depends on form>

</details>
