### ISSUE TITLE
Create Web APIs docs (Open API compatible)

### ISSUE THREAD

**Issue by anada10** [rnadigital/agentcloud#170]
> suggest a nodejs module to autogenerate openapi docs from docstring comments in nodejs

<details>

<summary>ChatGPT answer:</summary>

For generating OpenAPI documentation from docstring comments in Node.js, a popular and effective module is **`swagger-jsdoc`**. This module allows you to generate OpenAPI (formerly Swagger) documentation from comments in your code.

### `swagger-jsdoc`
- **Description**: `swagger-jsdoc` parses your JSDoc comments and generates the OpenAPI (Swagger) specification JSON file, which can be used to power tools like Swagger UI, ReDoc, and others.
- **Installation**:
	```bash
	npm install swagger-jsdoc
	```
- **Usage**:
	```javascript
	const swaggerJsdoc = require('swagger-jsdoc');
	const swaggerUi = require('swagger-ui-express');
	const express = require('express');
	const app = express();

	// Swagger definition
	const swaggerDefinition = {
		openapi: '3.0.0',
		info: {
			title: 'Your API Title',
			version: '1.0.0',
			description: 'API description',
		},
		servers: [
			{
				url: 'http://localhost:3000',
			},
		],
	};

	// Options for the swagger docs
	const options = {
		swaggerDefinition,
		// Path to the API docs
		apis: ['./routes/*.js'], // Files containing annotations as above
	};

	// Initialize swagger-jsdoc
	const swaggerSpec = swaggerJsdoc(options);

	// Serve swagger docs
	app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerSpec));

	app.listen(3000, () => {
		console.log('Server is running on http://localhost:3000');
	});
	```

### JSDoc Comment Example
In your Node.js code, you can add JSDoc comments like this:

```javascript
/**
 * @swagger
 * /users:
 *   get:
 *     summary: Retrieve a list of users
 *     description: Retrieve a list of users from the database
 *     responses:
 *       200:
 *         description: A list of users.
 *         content:
 *           application/json:
 *             schema:
 *               type: array
 *               items:
 *                 type: object
 */
app.get('/users', (req, res) => {
	// Your code here
	res.json([/* User data */]);
});
```

### Key Benefits:
- **Ease of Use**: Integrates seamlessly with Express and other Node.js frameworks.
- **Customization**: Offers flexible configuration options for customizing the generated documentation.
- **Supports OpenAPI 3.0**: The module is fully compatible with the latest OpenAPI standards.

`swagger-jsdoc` is widely used and well-documented, making it a solid choice for generating OpenAPI documentation from your Node.js project's docstrings.

</details>

https://www.npmjs.com/package/swagger-jsdoc

**Comment by anada10** [comment]
<img width="559" alt="image" src="https://github.com/rnadigital/agentcloud/assets/47853125/fa294a4b-cde9-44f2-902d-dc7321e31101">

Need ability for users to generate an API key and hit appropriate endpoints (shown in our mintlify docs)

**Comment by tomlynchRNA** [comment]
Updated OP description @NaderRNA
