### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by anada10** [rnadigital/agentcloud#18]
**Describe the bug**
TypeError: argument of type 'NoneType' is not iterable

**To Reproduce**
1. Start session
2. Enter prompt
3. Start watching stream

**Expected behavior**
No error 
**Screenshots**
<img width="1705" alt="image" src="https://github.com/rnadigital/agentcloud/assets/47853125/3b39c185-e955-4b17-ada9-c66e211773e9">

**Desktop (please complete the following information):**
 - OS: Mac Ventura
 - Browser Chrome
 - Version 118

**Additional context**
Docker
v0.0.1-812b094

**Comment by ragyabraham** [comment]
This issue has been resolved with this latest [commit](https://github.com/rnadigital/autogen/commit/c24030876537267aab0bb2d877122427767e5403)
