### ISSUE TITLE
Give users the option to choose their preferred vector db

### ISSUE THREAD

**Issue by ragyabraham** [rnadigital/agentcloud#229]
- Currently, users cannot choose which vector database to use. we restrict the use to only Qdrant
- this will create the modularity necessary to allow the use of multiple DBs and perhaps even a BYO
- this issue will mostly be concerned with creating the backend abstraction to enable the use of multiple vector DBs

**Comment by tomlynchRNA** [comment]
reopen if necessary, i think this is covered by #475
