### ISSUE TITLE
Error running multi agent, multi task app

### ISSUE THREAD

**Issue by anada10** [rnadigital/agentcloud#232]
**Describe the bug**
Stack trace:

2 validation errors for Delegate work to co-workerSchema
task
  field required (type=value_error.missing)
context
  field required (type=value_error.missing)

**To Reproduce**
1. Login to dev cloud
2. Enter andrew's team
3. Run the Uber Eat's brief writer multi agent, multi task app

**Expected behavior**
No bugs

**Screenshots**
<img width="1227" alt="Screenshot 2024-06-14 at 7 25 57 pm" src="https://github.com/rnadigital/agentcloud/assets/47853125/250356a6-eee5-46bd-9bb6-26617dee4caa">

**Comment by ragyabraham** [comment]
@charl3sj have you started working on this??

**Comment by charl3sj** [comment]
@ragyabraham Yes
