### ISSUE TITLE
[webapp] Update all form validations

### ISSUE THREAD

**Issue by tomlynchRNA** [rnadigital/agentcloud#239]
All user-facing routes need to be updated to either add or update existing form validation.

See `src/lib/utils/validationUtils.ts` for a util you can use to validate the request body. Open to switching to a more robust library if that will save time.

`ls -1 webapp/src/controllers`
- [x] account.ts
- [x] agent.ts
- [x] airbyte.ts
- [x] app.ts
- ~~asset.ts~~
- [x] datasource.ts
- [x] model.ts
- ~~notification.ts~~
- ~~oauth.ts~~
- [ ] session.ts
- [ ] stripe.ts
- [ ] task.ts
- [ ] team.ts
- [ ] tool.ts

**Comment by iandjx** [comment]
#277
