### ISSUE TITLE
Datasource does not finish processing

### ISSUE THREAD

**Issue by anada10** [rnadigital/agentcloud#245]
**Describe the bug**
The datasource has finished, but the loader is not reflecting this

**To Reproduce**
1. Add a datasource
2. wait for it to finish loading (by looking at the backend)

**Expected behavior**
Status completed or otherwise

**Screenshots**
<img width="1017" alt="Screenshot 2024-06-20 at 11 38 27 am" src="https://github.com/rnadigital/agentcloud/assets/47853125/fd0ac122-4337-468c-9df6-b1c8c6049423">

**Environment**
DEV - Cloud

**Comment by ragyabraham** [comment]
From what I saw yesterday the counter is incrementing in mongo but it's not showing up on the FE

**Comment by tomlynchRNA** [comment]
Issue is that webapp sets same docker for prod:

https://github.com/rnadigital/agentcloud/blob/e19ff6c75f44acfd5cdead679ee7b3ac0481453d/webapp/src/lib/airbyte/setup.ts#L148

Easy fix, just change it to be `${process.env.URL_APP}/webhook/sync-successful`

**Comment by ragyabraham** [comment]
> Issue is that webapp sets same for docker and prod:
> 
> 
> 
> https://github.com/rnadigital/agentcloud/blob/e19ff6c75f44acfd5cdead679ee7b3ac0481453d/webapp/src/lib/airbyte/setup.ts#L148
> 
> 
> 
> Because webapp doesn't get the webhook, it never knows the "total" count and thus stays forever pending
> 
> 
> 
> Easy fix, just change it to be `${process.env.URL_APP}/webhook/sync-successful`. 

@tomlynchRNA do you mind implementing this fix on the `cicd-testing` branch so I can test it on cloud

**Comment by tomlynchRNA** [comment]
@ragyabraham d82ba4a
