### ISSUE TITLE
[webapp] Improve airbyte connector setup form

### ISSUE THREAD

**Issue by tomlynchRNA** [rnadigital/agentcloud#248]
The form we use is based on this: https://github.com/m6io/rjsf-tailwind
See `webapp/src/components/rjsf`

We could:
- try to fix the existing form
- pick a different form library for jsonschema forms
- **try to take whatever form library airbyte uses**
- use a different approach completely

If we have to sacrifice matching our theme/tailwindcss for the form to just work, that's fine.

Known issues
- Some weirdness about `date` formats being parsed differently by the `ajv` library vs what airbyte APIs expect on their input, see the use of ajv and custom time format validation in `src/controllers/datasource.ts`.

cc @anada10 to assign

**Comment by ragyabraham** [comment]
@iandjx, please reach out to @tomlynchRNA if you have any webapp questions for this ticket. This is a priority ticket

**Comment by tomlynchRNA** [comment]
https://connectors.airbyte.com/files/generated_reports/connector_registry_report.json

**Comment by tomlynchRNA** [comment]
https://github.com/rnadigital/agentcloud/blob/eae9c374d79ef0c645fc77d5ae34a59142bae035/webapp/src/components/CreateDatasourceForm.tsx#L454
