### ISSUE TITLE
Chat App update

### ISSUE THREAD

**Issue by anada10** [rnadigital/agentcloud#251]
A chat app is the same as an Open AI GPT
It differes from a process app in two aspects
- It can only have ONE agent
- It does not have any tasks

This will use Langchain agents (as opposed to crewai)

**Chat App form**

The chat app form should have the following fields

**APP SETUP SECTION**
- Avatar
- Name
- Description
- Conversation Starters

**AGENT SECTION**
Search field: _Create a new agent or search for an existing one_
- Agent name
- Model (search field)
- System message 
- Datasource (search field)
- Tools (Search field)

**Comment by anada10** [comment]
Here is the docs for building a langchain chatbot for v0.2
https://python.langchain.com/v0.2/docs/tutorials/chatbot/

**Comment by tomlynchRNA** [comment]
> Here are the docs for building a langchain chatbot for v0.2 https://python.langchain.com/v0.2/docs/tutorials/chatbot/

https://github.com/langchain-ai/langgraph/blob/7a68cc63c4692d7c57b22d4ae88c5bb1d64b9d77/examples/create-react-agent-memory.ipynb

this is a good base
