### ISSUE TITLE
Clone Apps, Tasks, Agents, Tools

### ISSUE THREAD

**Issue by anada10** [rnadigital/agentcloud#254]
Problem
Currently if a user wants to make another version of an app/version/task they have to create new then copy and paste.

Solution
Add Clone buttons on the following
- Apps
- Agents
- Tasks
- Tools

When cloning apps users should be presented with a model which shows them all the dependencies of the app
Agents, Models, Tasks, Tools
And asks what they would like to clone and what they would like to map to existing

Interface idea CLONE / MAP TO EXISTING

- APP
       - [ ] NAME/ICON (CLONE/NEW)
       - [ ] DESCRIPTION (CLONE/NEW)
- AGENTS
       - [ ] AGENT 1  (MAP SELECTED) --> [SELECT/SEARCH AGENT]
       - [ ] AGENT 2 (CLONE SELECTED)
- TASKS
       - [ ] TASK 1  (MAP SELECTED) --> [SELECT/SEARCH TASK]
       - [ ] TASK 2 (CLONE SELECTED)
- TOOLS
       - [ ] TOOL 1  (MAP SELECTED) --> [SELECT/SEARCH TOOL]
       - [ ] TOOL 2 (CLONE SELECTED) 

... note if cloning Chat apps, three are no tasks.

**Comment by gorstagtully148** [comment]
Cloning apps, tasks, agents, and tools refers to the process of creating duplicate instances of these digital entities to enhance efficiency, scalability, and productivity in various workflows [Snake Aim tool app](https://snakeaimtool.org/). By cloning apps, users can run multiple instances of the same application simultaneously, allowing for better multitasking and parallel processing. Cloning tasks can streamline project management, enabling teams to replicate and delegate recurring activities quickly.
