### ISSUE TITLE
Web App UX - Sign up improvements

### ISSUE THREAD

**Issue by anada10** [rnadigital/agentcloud#270]
Clean up Sign up/Sign In experience as per design spec found here
https://www.figma.com/design/Extb1JRMQkwKftk9F4g0z2/Agent-Cloud-V2?node-id=5910-653&m=dev&t=N02uKMawSZSqJlIg-1

The changes at a high level include
- [ ] Minor Visual Enhancements
- [x] Sign in/up with Google
- [x] Email templates

See spec in these two sections in figma
<img width="479" alt="image" src="https://github.com/rnadigital/agentcloud/assets/47853125/7f6870f0-c07e-402f-be85-860af1001021">

**Comment by anada10** [comment]
@ragyabraham for allocation in backlog

**Comment by tomlynchRNA** [comment]
#288
