### ISSUE TITLE
Only OAI models are working in Chat apps

### ISSUE THREAD

**Issue by ragyabraham** [rnadigital/agentcloud#276]
**Describe the bug**
At the moment, only the OAI models are working within the chat app. 

**Plan**

- [ ] work to get all models working in the chat app @charl3sj 
- [x] In the meantime we will limit the pick list on the FE to only show OAI models when creating a chat app @tomlynchRNA 

linked to #142

**Comment by anada10** [comment]
As of today the current cross compatible vendors (works on both Process apps and chat apps) are
- OAI
- Anthropic
- Vertex

To add
- OAI (Azure)

To test
- Ollama (open source)

Currently only supported in process apps
- groq
- cohere

**Comment by tomlynchRNA** [comment]
stale
