### ISSUE TITLE
Ollama not working with chat apps

### ISSUE THREAD

**Issue by anada10** [rnadigital/agentcloud#351]
Currently ollama is not working with chat apps
![image](https://github.com/user-attachments/assets/54f6deb6-50ec-4747-b51d-9eb2c75539a9)
This validation error should be removed, and ollama should be added.

I managed to bypass this validation error by setting the Model via the agent screen, but this led to the following issue
![image](https://github.com/user-attachments/assets/9dfe56bb-8ef1-451f-a14f-5218b300272e)

A couple of things need to be fixed

- [ ] Ollama should work in chat apps and process apps
- [ ] Users should be able to enter custom model names on the models screen (since it's impossible to maintain a list of all the models. Only proviso is that not all models support tool calling. [Llaama3.1 does](https://ollama.com/library/llama3.1).

**Comment by charl3sj** [comment]
@tomlynchRNA Created https://github.com/rnadigital/agentcloud/pull/454 . 

Pending frontend change is to add [these](https://github.com/rnadigital/agentcloud/pull/454/files#diff-77a9c1c61d79d878884f42670de8fc79ce47bb8cf8bfdd78fac23cbe1acef432R49) models in frontend. I think it's okay to show all 3 models in both process and chat apps even though `llama3.1` and `llama3-groq-tool-use` perform differently in each.

**Comment by anada10** [comment]
@charl3sj I'm running latest master branch and unable to add ollama on a chat app
<img width="686" alt="Screenshot 2024-08-16 at 10 39 06 am" src="https://github.com/user-attachments/assets/12461d46-da40-403c-a332-3ae256f8dec6">

**Comment by anada10** [comment]
From testing it seems the two best performing models for tool usage are
- mistral-nemo:latest
- llama3-groq-tool-use:latest

These considerably outperform
- llama3.1:70b

This is in basic rag tests running on an Nvidia A100
