### ISSUE TITLE
Terminate [stop] button removed 

### ISSUE THREAD

**Issue by anada10** [rnadigital/agentcloud#352]
The terminate [stop] button has been removed.

Previously when pressing send, the send icon would change to a stop icon. This has been removed and users can no longer terminate/stop chats. Please re-introduce this.

<img width="1163" alt="Screenshot 2024-08-02 at 4 33 08 am" src="https://github.com/user-attachments/assets/8e79bb11-445b-484d-983c-78c48ff87e64">

**Comment by iandjx** [comment]
#353
