### ISSUE TITLE
Text is white (not visible) on day mode

### ISSUE THREAD

**Issue by anada10** [rnadigital/agentcloud#359]
There is white text in day mode, that is causing interface to be illegible in certain areas

- [ ] Session text
- [ ] App Cards
- [ ] Notification bell icon and text

not sure where else affected.

<img width="1512" alt="Screenshot 2024-08-02 at 1 39 10 pm" src="https://github.com/user-attachments/assets/78785adf-9c4f-49b0-9bf3-9b001ab0447e">

<img width="1085" alt="Screenshot 2024-08-02 at 1 38 43 pm" src="https://github.com/user-attachments/assets/5826dc2a-a270-4baf-8609-0d028a24c4d1">

<img width="386" alt="Screenshot 2024-08-02 at 1 43 58 pm" src="https://github.com/user-attachments/assets/74e69260-8734-4d83-b34c-daaf6c50049d">
notification

**Comment by anada10** [comment]
This seems to be an issue only when the **users system settings are on night mode** but the **app is on day mode**

**Comment by iandjx** [comment]
https://github.com/rnadigital/agentcloud/pull/362
