### ISSUE TITLE
Handle authenticated users on sign in and login pages

### ISSUE THREAD

**Issue by anada10** [rnadigital/agentcloud#378]
When a user who is authenticated visits the login or registration page, we can show a card which shows the org they are currently logged in to and let them click on it so that they can navigate directly to it.
@misri to provide design guidance here.

**Comment by anada10** [comment]
@misri can you design a component on 
agentcloud.dev/login
agentcloud.dev/register
that would show authenticated users an account that is already logged in

**Comment by misri** [comment]
https://www.figma.com/design/Extb1JRMQkwKftk9F4g0z2/Agent-Cloud-V2?node-id=6437-7514&t=P9yAanH488T889aw-0
