### ISSUE TITLE
Adding support for Retrival chat and function calling

### ISSUE THREAD

**Issue by agokrani** [rnadigital/agentcloud#38]
Hi, 

Saw your project really cool work. I was able to set it up locally. I am currently working on adding support for Retrival chat agents. Autogen already has examples for this. I would also like to add support for function calling in the group chat, do you guys have idea what would be the best way to approach this?

**Comment by ragyabraham** [comment]
@agokrani, that would be awesome! That is a really valuable feature, one that we have been talking about implementing. 

Just one thing, it's probably best to make this change in our [fork of autogen](https://github.com/rnadigital/autogen). If you want to chat about the design or if you have any questions feel free to hit me up on our discord. Thank you again for the contribution
