### ISSUE TITLE
Azure OpenAI integration

### ISSUE THREAD

**Issue by charl3sj** [rnadigital/agentcloud#383]
Frontend:
- Add `Azure OpenAI` platform and models
- Required model config params: `openai_api_key` and `azure_endpoint` ([refer](https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/models))
- Add to list of allowed models for chat apps

Backend:
- Integrate with both Process and Chat apps

List of models ([link](https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/models)):
![azure_openai_models](https://github.com/user-attachments/assets/b4515728-6b07-459d-94be-bf9305c68d7d)

**Comment by tomlynchRNA** [comment]
#386 you can push agent-backend changes to that branch, or merge it into your own and open a separate PR :slightly_smiling_face:
