### ISSUE TITLE
Allow other GPT models to be used

### ISSUE THREAD

**Issue by JABirchall** [rnadigital/agentcloud#39]
**Is your feature request related to a problem? Please describe.**
At the moment, agentcloud defaults to GPT-4 for all agents. 
However, some agents might not need GPT-4 and would work fine on GPT-3.5 or maybe the user wants to use GPT-3.5 for cost reasons.

**Describe the solution you'd like**
Lets the user choose what models agents should use. 

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by anada10** [comment]
Hey @JABirchall your wish is our command! :)
Check out our latest update. You can now enter your open ai credential, then select the credential you would like an agent to use AND the model. We've added GPT 4 turbo and GPT 3.5 turbo is also available.

1. Add your credential
![image](https://github.com/rnadigital/agentcloud/assets/47853125/6c6cebab-c7a0-4103-aaf1-56d7eb9b9fc6)

2. Create your agents (and select your credential and their model)
![image](https://github.com/rnadigital/agentcloud/assets/47853125/854bd0eb-4f9d-409c-bb2b-d5a37054fc7f)

3. Put your agents into groups
![image](https://github.com/rnadigital/agentcloud/assets/47853125/fad22d75-930b-4fcd-9749-c9f31b9f219e)

4. Select your group and start a session
![image](https://github.com/rnadigital/agentcloud/assets/47853125/baf897c4-1e14-46cb-bc0f-9baa9fbaff7f)
