### ISSUE TITLE
Amend crew's native human input tool to include websockets

### ISSUE THREAD

**Issue by ragyabraham** [rnadigital/agentcloud#406]
**Is your feature request related to a problem? Please describe.**
Currently we are using a custom human input tool and attaching it as a custom tool to the agent

**Describe the solution you'd like**
We should use the native crew human input, but we first need to add support for sending messages over websockets

**Additional context**
This should also provide some stability to process apps

**Comment by charl3sj** [comment]
Completed. https://github.com/rnadigital/agentcloud/pull/432
