### ISSUE TITLE
Get `pinecone-client` working 

### ISSUE THREAD

**Issue by ragyabraham** [rnadigital/agentcloud#416]
**Is your feature request related to a problem? Please describe.**
We need to get the `pinecone-client` working so we can use it in the `vector-db-proxy` app

**Describe the solution you'd like**
We have forked an archived [repo](https://github.com/rnadigital/pinecone-client) for this client. We need to revive it and get it working.

**Comment by ragyabraham** [comment]
This is a blocker to #331

**Comment by anada10** [comment]
God send!

https://github.com/pinecone-io/pinecone-rust-client?utm_content=303466540&utm_medium=social&utm_source=linkedin&hss_channel=lcp-20299330
