### ISSUE TITLE
Api keys screen

### ISSUE THREAD

**Issue by tomlynchRNA** [rnadigital/agentcloud#463]
- [x] ability to create a token with name, description, expiry, etc
- [x] ability to list and delete tokens
- [x] ability to regenerate

**Comment by tomlynchRNA** [comment]
cc @anada10 @misri please share designs when ready, functionality will be priority for now

**Comment by anada10** [comment]
> cc @anada10 @misri please share designs when ready, functionality will be priority for now
@tomlynchRNA @NaderRNA 
Please assume simple UX design for now, images shared on slack
- Create an API key (provide a name)
- Edit the name of the key
- Delete the key
- Copy the key (without viewing)

**Comment by NaderRNA** [comment]
@anada10 
On the last point, "Copy the key (without viewing)". Generally standard practice isn't to allow the user to see the key once it's been created.
On initial creation they'll get one chance to copy the key and after that there's no access to it again. If the user forgets the key or loses it then they simply make a new one (or for us we'll have an option to regenerate a new key with the same settings).
Groq, Github and most other providers don't allow this functionality.

It can be implemented but it's generally not done

**Comment by NaderRNA** [comment]
follow up from stand-up;
decision is to allow for:
-[] optional viewing of the token
-[] ability to copy the token
-[] no need to recreate the token
@tomlynchRNA confirm if I've missed/gotten anything wrong.
