### ISSUE TITLE
Select Datasource not working

### ISSUE THREAD

**Issue by frappierer** [rnadigital/agentcloud#467]
**Describe the bug**
See here https://jmp.sh/SYXZ6x1O
When I select a datasource i can't continue adding the needed data.

**To Reproduce**
See https://jmp.sh/SYXZ6x1O

**Expected behaviour**
Add Jira connection details

**Desktop (please complete the following information):**
Running via Docker Desktop on my Mac 14.1.2

**Comment by anada10** [comment]
@frappierer thanks for raising we are looking into this now
cc @tomlynchRNA

**Comment by anada10** [comment]
Hi @frappierer 
We are trying to replicate this but are unable to (as you can see below).
To replicate below I did
- git pull (master)
- Complete nuke of all my docker images (fresh install)
`docker system prune -a && docker volume prune -a && docker image prune -a`
- ran `install.sh`
- Confirmed Airbyte was running by visiting http://localhost:8000/
- Went to datasource screen clicked Jira
<img width="1349" alt="Screenshot 2024-08-21 at 3 40 30 pm" src="https://github.com/user-attachments/assets/a86e135e-8233-4787-986d-9f0f24dad47d">

Can you clarify

- [ ] Is airbyte running?
- [ ] What version are you running of Airbyte? I'm running 0.57.2
- [ ] What version are you running of Agent Cloud? I tested on latest at the time v1.5.0-git-b110608a

<img width="365" alt="Screenshot 2024-08-21 at 3 43 58 pm" src="https://github.com/user-attachments/assets/c3fb266b-95ce-40e0-b849-1316f250f9d0">

<img width="384" alt="Screenshot 2024-08-21 at 3 44 49 pm" src="https://github.com/user-attachments/assets/ce314401-7486-45d4-9d50-08eee3996f4b">

**Comment by frappierer** [comment]
Strange. It works now. At least i see the jira config screen. WIll do some tests later. Thanks!

**Comment by anada10** [comment]
Great thanks!
