### ISSUE TITLE
[FEATURE] allow users to stop and resume sessions

### ISSUE THREAD

**Issue by ragyabraham** [rnadigital/agentcloud#51]
**Is your feature request related to a problem? Please describe.**
Right now users can not stop and/or resume a session.

**Describe the solution you'd like**
Give users the ability to cancel their session and if they wish they can come back and resume at any time.

**Additional context**
work has been done to allow users to STOP a session. What is remaining is that they can no resume a session at any given time
![Screenshot 2023-11-17 at 12 50 22 pm](https://github.com/rnadigital/agentcloud/assets/52903382/38d4d4be-343c-4b20-bb55-d6d5ba0b5b78)

**Comment by anada10** [comment]
https://github.com/rnadigital/agentcloud/issues/23 linked to this issue
