### ISSUE TITLE
Update chunked rows

### ISSUE THREAD

**Issue by ragyabraham** [rnadigital/agentcloud#550]
**Is your feature request related to a problem? Please describe.**

When a chunking strategy is applied to a synced row, a single row results in several vector points. These points have been randomly assigned UUIDs as vector point indexes. To update these points, we need to be able to query and delete the existing points so as not to create duplicates. 

**Describe the solution you'd like**

For every point associated with the original row, we will store the primary key in the `index` field. This field will be used to perform a vector search and delete prior to upsert operation. This will ensure that points are updated rather than duplicated.

**Additional context**

We will use the `SearchType::ChunkedRow` in the `vector-db-proxy` app to indicate that this operation is required to happen

**Comment by tomlynchRNA** [comment]
@ragyabraham seems like when I update a row to change the cursor field and one of the metadata fields (primary key stays the same), it still doesn't delete the old points from qdrant.

datasource:
![image](https://github.com/user-attachments/assets/aece4c55-1c63-4e6f-96ae-6375051aaf3e)

I have these 6 rows in bq:
![image](https://github.com/user-attachments/assets/de6ca401-aa5d-41de-8f7e-abc76ece7992)

I sync and get 6 points in qdrant:
![image](https://github.com/user-attachments/assets/267e7359-0dec-4535-bba4-fa034b46b96e)

Then I update one of the rows:
![image](https://github.com/user-attachments/assets/31402608-020e-4ed0-8756-1cb33f3a92fc)

Then sync again and have 7 points in qdrant, with both old and new versions of the "#StayProductive" one:
![image](https://github.com/user-attachments/assets/d8c3a0fa-f9da-4085-b1ec-a3f250c135b6)
![image](https://github.com/user-attachments/assets/2651f18c-9bab-4575-88c4-ca7d6d062778)

Also note: my chunkingConfig is set to `max_characters: 10` and `new_after_n_chars: 10` but the page_content is definitely more than 10 characters. Not sure if that's us or unstructured. I'm using the unstructured cloud without key.
