### ISSUE TITLE
Row by row chunking invalid inputs error

### ISSUE THREAD

**Issue by anada10** [rnadigital/agentcloud#551]
Attempting to do a row by row chunk results in an invalid inputs error.
![image](https://github.com/user-attachments/assets/f2c7762e-5795-4971-ae5c-fbcec049fbc2)
![image](https://github.com/user-attachments/assets/08f05940-6742-4a8c-8c2b-7079a48560e4)

**Comment by tomlynchRNA** [comment]
Invalid inputs for this API only happens if the datasource or selected embedding model no longer exists.

Can't repro on app., was able to embed 2 datasources w/ chunking and your request looks fine.

Goingto build app. from develop branch and you can try it again.
