### ISSUE TITLE
Fix agent-backend not able to be terminated by SIGINT (commonly "ctrl+c" on nix)

### ISSUE THREAD

**Issue by tomlynchRNA** [rnadigital/agentcloud#553]
This may be related to redis, mongodb, or socket.io maintaining connections after a SIGINT and not being closed/cleand up properly.

See the cleanup method in webapp for a basic idea:
https://github.com/rnadigital/agentcloud/blob/38f910e43e03f7bbe0583ce6f319458e976f61f4/webapp/src/server.ts#L107
the webapp also cleans up socket.io because the http server and socketio server close together.

**Comment by charl3sj** [comment]
https://github.com/rnadigital/agentcloud/pull/572
