### ISSUE TITLE
[FEATURE] Enable single agent rag

### ISSUE THREAD

**Issue by ragyabraham** [rnadigital/agentcloud#69]
**Is your feature request related to a problem? Please describe.**
currently, it is not possible to have a single agent rag flow in the platform. RAG addresses a number of use cases and is a highly sought-after feature in the platform.
**Describe the solution you'd like**
Using the canopy library from Pinecone we will implement a production-grade rag pipeline

**Comment by shanmu-raoyunfei** [comment]
This is a great feature. RAG can be configured by any agent

**Comment by pebeid** [comment]
I've integrated RAG into the agent execution flow; however, two tasks remain:
* Cleanup the code so there isn't much orphaned code.
* Allow multiple datasources per agent (currently it's 1:1)
